apiVersion: cloud-copilot.operator.io/v1alpha1
kind: CloudService
metadata:
  name: "web-cloudservice"
  namespace: "default"
spec:
  replicas: 3
  request_cpu: 1
  limit_cpu: 2
  request_memory: 1024
  limit_memory: 2048
  ports:
    - ingress_path: "/api"
      protocol: "TCP"
      container_port: 8080
