---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudservices/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudservices/status
  verbs:
  - get
  - patch
  - update
