---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudappreleases
  - cloudapps
  - cloudclusters
  - cloudprojects
  - cloudservices
  - cloudworkflows
  - cloudworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudappreleases/finalizers
  - cloudapps/finalizers
  - cloudclusters/finalizers
  - cloudprojects/finalizers
  - cloudservices/finalizers
  - cloudworkflows/finalizers
  - cloudworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-copilot.operator.io
  resources:
  - cloudappreleases/status
  - cloudapps/status
  - cloudclusters/status
  - cloudprojects/status
  - cloudservices/status
  - cloudworkflows/status
  - cloudworkspaces/status
  verbs:
  - get
  - patch
  - update
