apiVersion: cloud-copilot.operator.io/v1alpha1
kind: CloudWorkflow
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudworkflow-sample
spec:
  # TODO(user): Add fields here
