apiVersion: operator.ocean.io/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: operatorapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operatorapp
  name: app-sample
spec:
  # TODO(user): Add fields here
