apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
  labels:
    app: {{.ObjectMeta.Name}}
spec:
  replicas: {{.Spec.Service.Replicas}}
  selector:
    matchLabels:
      app: {{.ObjectMeta.Name}}
  template:
    metadata:
      labels:
        app: {{.ObjectMeta.Name}}
    spec:
      containers:
      - name: {{.ObjectMeta.Name}}
        image: {{.Spec.Service.Image}}
        resources:
          requests:
            memory: {{.Spec.Service.Memory}}
            cpu: {{.Spec.Service.CPU}}
          limits:
            memory: {{.Spec.Service.LimitMemory}}
            cpu: {{.Spec.Service.LimitCPU}}
            {{if ne .Spec.Service.GPU ""}}
            nvidia.com/gpu: {{.Spec.Service.GPU}}
            {{end}}
        ports:
          {{- range .Spec.Service.Ports}}
          - containerPort: {{.ContainerPort}}
          {{- end}}
        volumeMounts:
        - mountPath: /etc/app
          name: {{.ObjectMeta.Name}}-config-volume
        - mountPath: /etc/secret
          name: {{.ObjectMeta.Name}}-secret-volume
      volumes:
      - name: {{.ObjectMeta.Name}}-config-volume
        configMap:
          name: {{.ObjectMeta.Name}}
      - name: {{.ObjectMeta.Name}}-secret-volume
        secret:
          secretName: {{.ObjectMeta.Name}}