apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  rules:
    - host: {{.ObjectMeta.Name}}
      http:
        paths:
          {{- range .Spec.Service.Ports}}
          - path: {{.IngressPath}}
            pathType: Prefix
            backend:
              service:
                name: {{$.ObjectMeta.Name}}
                port:
                  number: {{.ContainerPort}}
          {{end}}
  ingressClassName: traefik