apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  selector:
    app: {{.ObjectMeta.Name}}
  ports:
    {{- range .Spec.Service.Ports}}
    - name: http
      protocol: TCP
      port: {{.ContainerPort}}
      targetPort: {{.ContainerPort}}
    {{- end}}