apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{.Name}}-pool
  namespace: {{.Namespace}}
spec:
  addresses:
  - {{.LbIpStart}}-{{.LbIpEnd}}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  ipAddressPools:
  - {{.Name}}-pool