---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  selector:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
    {{- range .Spec.Ports }}
    - name: {{ .Name }}
      protocol: {{ .Protocol }}
      port: {{ .ContainerPort }}
      targetPort: {{ .ContainerPort }}
    {{- end }}
{{- if .Spec.CanaryDeployment.Image }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-canary
  namespace: {{ .Namespace }}
  labels:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    version: canary
spec:
  selector:
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    version: canary
  ports:
    {{- range .Spec.Ports }}
    - name: {{ .Name }}
      protocol: {{ .Protocol }}
      port: {{ .ContainerPort }}
      targetPort: {{ .ContainerPort }}
    {{- end }}
{{- end }}